bind_addr = ":8080"
log_level = "debug"
database_url = "host=localhost dbname=restapi_dev sslmode=disable user=postgres"
session_key = "QeThWmZq4t7w!z%C*F-JaNcRfUjXn2r5u8x/A?D(G+KbPeSgVkYp3s6v9y$B&E)H@McQfTjWmZq4t7w!z%C*F-JaNdRgUkXp2r5u8x/A?D(G+KbPeShVmYq3t6v9y$B&"